### ISSUE TITLE
beta-values vs M-values for lmFit

### ISSUE THREAD

**Issue by christpa** [ammegandchips/PACE_Paternal_BMI#1]
Hi Gemma, I have a small concern in the analysis plan for the Pat BMI when it comes to the use of beta-values with lmFit. To quote from the R-help page for lmFit

> If  ‘object’ is a matrix then it should contain log-ratios or log-expression data with rows corresponding to probes and columns to arrays. 

How does this work when the input is restricted between [0,1] and not mapped to log-values? 
I would suggest a small simulation or test to find out if this works well with beta-values as well. 

Christian

**Comment by ammegandchips** [comment]
Hi Christian,
Thanks for flagging this. lmFit does exactly the same as CpGassoc (supposedly designed for methylation data) and lm, in that it just applies linear regression to each row of the matrix. I checked the results using CpGassoc, a function that applies lm to every row, and lmFit - all give identical results. I think the issue of whether using beta values is the "correct" statistic to use with linear regression is a wider issue that applies to all the methods we use. It's pretty universally accepted though, and gives us interpretable coefficients.

**Comment by christpa** [comment]
I agree that the model was specified correct, and that using beta-values gives more interpretable results. My concern was more if the assumptions would hold hold for beta-values. 

I also noticed that lmFit has a robust option for `rlm()` like regression, should we consider that over `lm`?

**Comment by ammegandchips** [comment]
I think you can argue it either way, but I decided to keep it simple with lm because our original reasons for going for rlm were because of outliers in the methylation data, but now we deal with that using the IQR3 removal. The analysis is pretty "stringent" as it is, with adjustment for 20 SVs, so I think we're already minimising our chances of finding false positives :)

**Comment by christpa** [comment]
Ok, good. 
I'm sufficiently convinced.
